version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: klowhub_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: klowhub
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: klowhub_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@klowhub.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  db_data:
