export const GET_PROJECTS_ENDPOINT = process.env.NEXT_PUBLIC_PROJECTS_URL;
export const GET_COURSES_ENDPOINT = process.env.NEXT_PUBLIC_COURSES_URL;
export const GET_APPLICATIONS_ENDPOINT = process.env.NEXT_PUBLIC_APPLICATIONS_URL;
