enum applicationFormTypes {
  SET_GENERAL_DATA = "SET_GENERAL_DATA",
  SET_DETAILS_DATA = "SET_DETAILS_DATA",
  SET_MEDIA_DATA = "SET_MEDIA_DATA",
  SET_PROMOTION_DATA = "SET_PROMOTION_DATA",
}

export default applicationFormTypes
