enum courseFormTypes {
  SET_GENERAL_DATA = "SET_GENERAL_DATA",
  SET_DETAILS_DATA = "SET_DETAILS_DATA",
  SET_MODULES_DATA = "SET_MODULES_DATA",
  ADD_NEW_MODULE = "ADD_NEW_MODULE",
  SET_PROMOTION_DATA = "SET_PROMOTION_DATA",

  SET_GENERAL_DATA_MOCK = "SET_GENERAL_DATA_MOCK",
  SET_DETAILS_DATA_MOCK = "SET_DETAILS_DATA_MOCK",
  SET_MODULES_DATA_MOCK = "SET_MODULES_DATA_MOCK",
}

export default courseFormTypes
