export enum CoreContent {
  UX_UI = 'ux-ui',
  DATABASES = 'databases',
  EXPRESSIONS_AND_FORMULAS = 'expressions-and-formulas',
  AUTOMATION = 'automation',
  WORKFLOWS = 'workflows',
  ACTIONS_BEHAVIOR = 'actions-behavior',
  SECURITY_ACCESIBILITY = 'security-accesibility',
  GENERAL = 'general',
}

export enum Functionalities {
  CALENDARIO = 'calendario',
  GENERACION_DE_PDF = 'generacion-de-pdf',
  REPORTES_AUTOMATICOS = 'reportes-automaticos',
  CHATBOT_BOT = 'chatbot-bot',
  EMAILS = 'emails',
  SMS = 'sms',
  NOTIFICACIONES_PUSH = 'notificaciones-push',
  GENERACION_Y_ESCANEO_QR = 'generacion-y-escaneo-qr',
  GEOLOCALIZACION = 'geolocalizacion',
  OCR = 'ocr',
  MACHINE_LEARNING = 'machine-learning',
  ESTADISTICAS_DE_USO = 'estadisticas-de-uso',
  DASHBOARD_REPORTES_Y_ANALISIS = 'dashboard-reportes-y-analisis',
  GESTION_DE_USUARIOS = 'gestion-de-usuarios',
  REPORTING_AVANZADO = 'reporting-avanzado',
  INTEGRACION_DE_DATOS = 'integracion-de-datos',
  GESTION_DE_PERMISOS = 'gestion-de-permisos',
  ANALISIS_DE_DATOS = 'analisis-de-datos',
  OPTIMIZACION_PERFORMANCE = 'optimizacion-performance',
  DESPLIEGUE_DEPLOY = 'despliegue-deploy',
  IMPORTACION_EXPORTACION_DE_DATOS = 'importacion-exportacion-de-datos',
  FIRMAS_DIGITALES = 'firmas-digitales',
  ESCANEO_DE_DOCUMENTOS = 'escaneo-de-documentos',
  MONITOR_DE_AUTOMATIZACIONES = 'monitor-de-automatizaciones',
  HISTORIAL_DE_AUDITORIA = 'historial-de-auditoria',
  API_INTEGRACIONES = 'api-integraciones',
}

export enum Sector {
  INDUSTRIA = 'industria',
  GESTION_DEL_TIEMPO = 'gestion-del-tiempo',
  GESTION_DE_PROYECTOS = 'gestion-de-proyectos',
  GESTION_DE_INVENTARIOS = 'gestion-de-inventarios',
  VENTAS_Y_CRM = 'ventas-y-crm',
  OBRAS_Y_CONSTRUCCION = 'obras-y-construccion',
  LOGISTICA_Y_TRANSPORTE = 'logistica-y-transporte',
  SERVICIOS_PROFESIONALES = 'servicios-profesionales',
  MARKETING_DIGITAL = 'marketing-digital',
  E_COMMERCE = 'e-commerce',
  ENTRETENIMIENTO_Y_MEDIOS = 'entretenimiento-y-medios',
  SEGURIDAD_Y_VIGILANCIA = 'seguridad-y-vigilancia',
  INVESTIGACION_Y_DESARROLLO = 'investigacion-y-desarrollo',
  AGRICULTURA_Y_MEDIO_AMBIENTE = 'agricultura-y-medio-ambiente',
  ADMINISTRACION = 'administracion',
}

export enum ToolsAndPlatform {
  GOOGLE_SHEETS = 'google-sheets',
  LOOKER_STUDIO = 'looker-studio',
  MYSQL = 'mysql',
  POSTGRESQL = 'postgresql',
  SALESFORCE = 'salesforce',
  AIRTABLE = 'airtable',
  DROPBOX = 'dropbox',
  BOX = 'box',
  GOOGLE_ANALYTICS = 'google-analytics',
  ZAPIER = 'zapier',
  WORDPRESS = 'wordpress',
  SHOPIFY = 'shopify',
  WHATSAPP_API = 'whatsapp-api',
  POWER_BI = 'power-bi',
  TWILIO = 'twilio',
  TRELLO = 'trello',
  GOOGLE_CALENDAR = 'google-calendar',
  GOOGLE_DRIVE = 'google-drive',
  GOOGLE_MAPS = 'google-maps',
}

export enum Tags {
  PLATAFORMA_DE_CURSOS = 'plataforma-de-cursos',
  APLICACIONES_SIN_CODIGO = 'aplicaciones-sin-codigo',
  DESARROLLADORES_NOCODE = 'desarrolladores-nocode',
  POWERAPPS_PARA_EMPRESAS = 'powerapps-para-empresas',
  APPSHEET_PARA_NEGOCIOS = 'appsheet-para-negocios',
  AUTOMATIZACION_DE_TAREAS = 'automatizacion-de-tareas',
  APPS_DE_PRODUCTIVIDAD = 'apps-de-productividad',
  TECNOLOGIA_PARA_EMPRESAS = 'tecnologia-para-empresas',
  HERRAMIENTAS_NOCODE = 'herramientas-nocode',
  CREACION_DE_APLICACIONES = 'creacion-de-aplicaciones',
}
