import type { Metadata } from "next";
import StoreCtxProvider from "@/contexts/store/store-provider";
import localFont from "next/font/local";
import "./../globals.css";
import { Footer } from "@/components/footer/footer.component";

import { Toaster } from "sonner"; import { Inter } from "next/font/google";
const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "400", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "KlowHub",
  description: "Generated by h3-03-klowhub",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <Toaster richColors />

        <div className="w-full h-full">
          <StoreCtxProvider>
            {children}
          </StoreCtxProvider>
        </div>
        <div className="h-full w-full bg-[#201d42] -mt-8">
          <div className="relative z-10">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
