enum courseFormTypes {
  SET_GENERAL_DATA = "SET_GENERAL_DATA",
  SET_DETAILS_DATA = "SET_DETAILS_DATA",
  SET_MODULES_DATA = "SET_MODULES_DATA",
  ADD_NEW_MODULE = "ADD_NEW_MODULE",
  SET_PROMOTION_DATA = "SET_PROMOTION_DATA",
}

export default courseFormTypes
