export type IconTypes =
  | "more-vertical"
  | "star"
  | "rated-star"
  | "shopping-cart"
  | "power-apps"
  | "app-sheet"
  | "close"
  | "list-filter"
  | "heart"
  | "proyector"
  | "user"
  | "clock"
  | "arrow"
