export type Sectors = 
  | "industria"
  | "gestión-del-tiempo"
  | "gestión-de-proyectos"
  | "gestión-de-inventarios"
  | "ventas-y-crm"
  | "obras-y-construcción"
  | "logística-y-transporte"
  | "servicios-profesionales"
  | "marketing-digital"
  | "e_commerce"
  | "entretenimiento-y-medios"
  | "seguridad-y-vigilancia"
  | "investigación-y-desarrollo"
  | "agricultura-y-medio-ambiente"
  | "administración"

export type Funcionalitites =
  | "calendario"
  | "generación-de-pdf"
  | "reportes-automáticos"
  | "chatbot-(bot)"
  | "emails"
  | "sms"
  | "notificaciones-push"
  | "generación-y-escaneo-qr"
  | "geolocalización"
  | "ocr"
  | "machine-learning"
  | "estadísticas-de-uso"
  | "dashboard_reportes-y-análisis"
  | "gestión-de-usuarios"
  | "reporting-avanzado"
  | "integración-de-datos"
  | "gestión-de-permisos"
  | "análisis-de-datos"
  | "optimización_performance"
  | "despliegue_deploy"
  | "importación_exportación-de-datos"
  | "firmas-digitales"
  | "escaneo-de-documentos"
  | "monitor-de-automatizaciones"
  | "historial-de-auditoría"
  | "api_integraciones"

export type ToolsAndPlatforms =
  | "google-sheets"
  | "looker-studio"
  | "mysql"
  | "postgresql"
  | "salesforce"
  | "airtable"
  | "dropbox"
  | "box"
  | "google-analytics"
  | "zapier"
  | "wordpress"
  | "shopify"
  | "whatsapp-api"
  | "power-bi"
  | "twilio"
  | "trello"
  | "google-calendar"
  | "google-drive"
  | "google-maps"

export type ContentType =
  | "curso"
  | "leccion"

export type CourseDificulty = 
  | "basic"
  | "intermediate"

export type CoreContent =
  | "ux-ui"
  | "databases"
  | "expressions-and-formulas"
  | "automation"
  | "workflows"
  | "actions-behavior"
  | "security-accesibility"
  | "general"

